### ISSUE TITLE
missing playground

### ISSUE THREAD

**Issue by Alken0** [felixhir/pages-test#2]
I would like to use the emulator during my lecture. Sadly I'm only on my phone and can't compile your project. Could you please host it?

**Comment by felixhir** [comment]
Please be aware that this project is a clone of the [actual repository](https://github.com/moorts/name_is_wip) where I simply tried getting GitHub pages to run. I will change the visibility soon to avoid further confusion.

The good news is, you can access the emulator [here](https://moorts.github.io/name_is_wip/) to try it out for yourself. 
Another point worth mentioning: This project was done for some time during the contributors time at university, which has now passed. Therefore the app is not maintained anymore.

I hope this helps!

**Comment by Alken0** [comment]
Thank you very much, I love it!
